teams = [
    {'name': 'Cardinals', 'id': '22'}, 
    {'name': 'Falcons', 'id': '1'}, 
    {'name': 'Ravens', 'id': '33'}, 
    {'name': 'Bills', 'id': '2'}, 
    {'name': 'Panthers', 'id': '29'}, 
    {'name': 'Bears', 'id': '3'}, 
    {'name': 'Bengals', 'id': '4'}, 
    {'name': 'Browns', 'id': '5'}, 
    {'name': 'Cowboys', 'id': '6'}, 
    {'name': 'Broncos', 'id': '7'}, 
    {'name': 'Lions', 'id': '8'}, 
    {'name': 'Packers', 'id': '9'}, 
    {'name': 'Texans', 'id': '34'}, 
    {'name': 'Colts', 'id': '11'}, 
    {'name': 'Jaguars', 'id': '30'}, 
    {'name': 'Chiefs', 'id': '12'}, 
    {'name': 'Raiders', 'id': '13'}, 
    {'name': 'Chargers', 'id': '24'}, 
    {'name': 'Rams', 'id': '14'}, 
    {'name': 'Dolphins', 'id': '15'}, 
    {'name': 'Vikings', 'id': '16'}, 
    {'name': 'Patriots', 'id': '17'}, 
    {'name': 'Saints', 'id': '18'}, 
    {'name': 'Giants', 'id': '19'}, 
    {'name': 'Jets', 'id': '20'}, 
    {'name': 'Eagles', 'id': '21'}, 
    {'name': 'Steelers', 'id': '23'}, 
    {'name': '49ers', 'id': '25'}, 
    {'name': 'Seahawks', 'id': '26'}, 
    {'name': 'Buccaneers', 'id': '27'}, 
    {'name': 'Titans', 'id': '10'}, 
    {'name': 'Commanders', 'id': '28'}
]

positions = [
    {'name': 'Quarterback', 'id': '8'}, 
    {'name': 'Wide Receiver', 'id': '1'}, 
    {'name': 'Running Back', 'id': '9'}, 
    {'name': 'Fullback', 'id': '10'}, 
    {'name': 'Tight End', 'id': '7'}, 
    {'name': 'Running Back', 'id': '9'},
    {'name': 'Place Kicker', 'id': '22'}
] 